import appLogo from 'src/assets/logos/logo-femsa.png';

export const config = {
	dataConfig: [
		{
			baseUrl: 'https://api.rmtecho.com.br/api',
			baseUrlReport: 'https://api.rmtecho.com.br/api',
			database: 'BIS',
		},
		{
			section1Text: 'Portaria',
			preRegisterPath: '/precadastro',
			preRegisterText: 'Pré-Cadastro',
			registerPath: null,
			registerText: null,
			registerBBPath: '/cadastrobb',
			registerBBText: 'Cadastro',
			personRegisterPath: '/cadastrocolaborador',
			personRegisterText: 'Cadastro Colaborador',
			// HIK
			preRegisterHIKPath: null,
			preRegisterHIKText: null,
			registerHIKPath: null,
			registerHIKText: null,
			checkinHIKPath: null,
			checkinHIKText: null,
			personRegisterHIKPath: null,
			personRegisterHIKText: null,
		},
		// Side bar's events section
		{
			section2Text: 'Eventos',
			accessReportText: 'Eventos de acesso',
			accessReportPath: '/relatorio',
		},
		{
			section3Text: 'Dashboard',
			dashboardText: 'Refeições',
			dashboardPath: '/dashrefeicao',
		}

	],
	stylesConfig: [
		{
			loginLogo: appLogo,
			loginDarkModeLogo: appLogo,
			loginLogoWidth: '75', // Defines login logo height - 25, 50, 75, 100, auto
			homeLogo: appLogo,
			homeDarkModeLogo: appLogo,
			homeLogoHeight: '25', // Defines homepage logo height - 25, 50, 75, 100, auto
			asideLogo: appLogo,
			asideDarkModeLogo: appLogo,
			asideMarginTop: '3', // Defines margin top for aside logo
			asideMarginLeft: '2', // Defines margin left for aside logo
			asideColNumber: '11', // Defines number of columns in aside logo component -> it goes from 1 to 12
			footerLogo: '',
			footerDarkModeLogo: '',
			footerLogoHeight: 30, // Must be a number
			headerLogo: '',
			headerDarkModeLogo: '',
			headerColNumber: '10', // Defines number of columns in header logo component -> it goes from 1 to 12
			headerLogoWidth: '25', 
			headerMarginTop: '0',
			headerMarginLeft: '0'// Defines header logo width - 25, 50, 75, 100, auto
		},
		// Pre-register styles
		{
			photoField: true,
			snapshotField: false,
			documentField: true,
			nameField: true,
			phoneField: true,
			cellPhoneField: true,
			unitField: false,
			emailField: false,
			companyField: true,
			cnpjField: true,
			addCompanyButton: true,
			entryDateField: true,
			exitDateField: true,
			releaseTypeField: true,
			codeField: false,
			cardNumberField: false,
			authorizationField: false,
			authorizationMultiSelectField: true,
			serialPortButton: false,
			authorizerNameField: true,
			authorizerCompanyField: true,
			branchLineField: true,
			profile: true,
			persclassField: true,
		},
		// Register page styles
		{
			photoField: true,
			snapshotField: false,
			documentField: true,
			nameField: true,
			phoneField: true,
			cellPhoneField: true,
			unitField: false,
			unitFieldBB: false,
			emailField: false,
			companyField: true,
			cnpjField: true,
			addCompanyButton: true,
			entryDateField: true,
			exitDateField: true,
			releaseTypeField: false,
			codeField: false,
			cardNumberField: true,
			cardSiteCode: true,
			profileField: false,
			authorizationField: false,
			authorizationMultiSelectField: true,
			serialPortButton: false,
			authorizerNameField: true,
			authorizerCompanyField: true,
			branchLineField: true,
			profile: false,
			persclassField: true,
			visitorType: true
		},
		// Access report page form fields
		{
			initialDateField: true,
			initialDateFieldText: 'Data inicial',
			endDateField: true,
			endDateFieldText: 'Data final',
			eventTypeField: true,
			peopleField: true,
			peopleText: 'Grupo de pessoas',
			accessTypeField: true,
			accessTypeText: 'Tipo de acesso',
			clearanceField: true,
			clearanceText: 'Tipo de liberação',
			companyField: true,
			companyText: 'Empresa',
			sectorField: true,
			sectorText: 'Setor',
			personTypeField: true,
			personTypeText: 'Tipo de pessoa',
			searchPersonDocOrNameField: true,
			searchPersonDocOrNameText: 'Número do documento ou nome da pessoa',
			personNameField: true,
			personNameText: 'Nome',
			visitorDocField: true,
			visitorDocText: 'Documento',
			accessReaderField: true,
			accessReaderText: 'Leitora de acesso',
			accessUnitField: true,
			accessUnitText: 'Unidade',
		},
		// Person Register page styles
		{
			photoField: true,
			documentField: true,
			nameField: true,
			phoneField: false,
			cellPhoneField: true,
			unitField: false,
			emailField: true,
			companyField: false,
			cnpjField: false,
			addCompanyButton: false,
			entryDateField: false,
			exitDateField: false,
			releaseTypeField: false,
			cardSiteCode: true,
			cardNumberField: true,
			authorizationField: false,
			authorizationMultiSelectField: false,
			serialPortButton: false,
			authorizerNameField: false,
			authorizerCompanyField: false,
			branchLineField: false,
			authorizerCard: false
		},
	],
	
};
